version: 0.0.0+{build}

skip_tags: true

skip_branch_with_pr: true

build:
  verbosity: minimal

test: false

environment:
  WHISKEY_DISABLE_ERROR_FORMAT: True
  matrix:
  - job_name: Build
    job_group: build
    appveyor_build_worker_image: Visual Studio 2022

  # Windows
  # https://www.appveyor.com/docs/windows-images-software/
  - job_name: Test Windows PowerShell 5.1 (.NET 4.6.2) on Windows Server 2012 R2
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2013
    job_depends_on: Build

  - job_name: Test Windows PowerShell 5.1 on Windows Server 2016
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2017
    job_depends_on: Build

  - job_name: Test Windows PowerShell 5.1 on Windows Server 2019
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2022
    job_depends_on: Build

  # PowerShell 7 on Windows only available on Windows Server 2019 build image
  - job_name: Test PowerShell 7 on Windows Server 2019
    job_group: pwsh
    appveyor_build_worker_image: Visual Studio 2022
    job_depends_on: Build

  # PowerShell 6 on Windows only available on Windows Server 2016 build image
  - job_name: Test PowerShell 6 on Windows Server 2016
    job_group: pwsh
    appveyor_build_worker_image: Visual Studio 2017
    job_depends_on: Build

artifacts:
- path: .output\*

for:
# Build in Windows PowerShell
- matrix:
    only:
    - job_group: build
  build_script:
  - ps: |
        $ProgressPreference = 'SilentlyContinue'
        iwr https://raw.githubusercontent.com/webmd-health-services/Prism/main/Scripts/init.ps1 | iex | Format-Table
        .\build.ps1

# Test on powershell.exe
- matrix:
    only:
    - job_group: ps
  build_script:
  - ps: &build_script |
        $ProgressPreference = 'SilentlyContinue'
        iwr https://raw.githubusercontent.com/webmd-health-services/Prism/main/Scripts/init.ps1 | iex | Format-Table
        .\Get-ModuleZipArtifact.ps1 -Token $env:APPVEYOR_BEARER_TOKEN -JobName 'Build'
        .\build.ps1 -PipelineName 'Test'

# Test on pwsh.exe
- matrix:
    only:
    - job_group: pwsh
  build_script:
  - pwsh: *build_script
